### PR TITLE
Fix BigWigs packager integration.

### PR DESCRIPTION
**Pull request by QartemisT**

### CODE REVIEW

**Comment by QartemisT** [comment]
This should fix your upload problems not happening automagically :)

**Review by davidcraig — APPROVED** [review]

**Comment by davidcraig** [comment]
wasn't sure if it was meant to make a github release as well, nothing seems to be happening with it :D I can see the file is being generated however, just doesn't seem to go anywhere :)

**Comment by QartemisT** [comment]
Yeh the way you trigger the packager is either;
a) Create and push any edit, to create an "alpha" release (You have this disabled)
b) Create a github release to create a "release" build. All of the github information gets put in (e.g. files, changelog) etc.

**Comment by davidcraig** [comment]
how do I have alpha disabled?

**Comment by QartemisT** [comment]
https://github.com/ps-wow/AdiBags_SniperClassic/blob/master/.github/workflows/build-classic.yml#L8

This section here basically means it will only package when you push a tag :)

If you wanted to publish an alpha for every commit you do, you would set tags to "*"

**Pull request merged**
